trigger:
  branches:
    include:
    - main

variables:
- name: JFROG_CLI_LOG_LEVEL
  value: 'DEBUG'

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: pwd
      displayName: 'Print Current Working Directory'

    - task: JFrogNpm@1
      inputs:
        command: 'install'
        artifactoryConnection: 'harithaa-artifactory-v2-hts2'
        sourceRepo: 'harithaa-npm'
        collectBuildInfo: true
        threads: '1'
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'

    - task: JFrogPublishBuildInfo@1
      inputs:
        artifactoryConnection: 'harithaa-artifactory-v2-hts2'
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
    - task: JFrogBuildScan@1
      inputs:
        xrayConnection: 'harithaa-xray'
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
        allowFailBuild: true
        vuln: true

    - task: JFrogNpm@1
      inputs:
        command: 'pack and publish'
        artifactoryConnection: 'harithaa-artifactory-v2-hts2'
        targetRepo: 'harithaa-npm-local'
        workingFolder: '/home/vsts/work/1/s'
        collectBuildInfo: true
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
